### ISSUE TITLE
Ajax call for logged in user

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/Project_3#20]
I'm trying to make an AJAX call in my scripts file that will load in the data for the current logged in user. To start, I was just trying to grab data for all users in the database (using past hw examples), but I'm getting users undefined in this code: 

function getAllFavorites(callback) {
  callback = callback || function(){};
  $.ajax({
  url: '/',
  success: function(data){
    var users = data.users;
    console.log(users);  <<<<< ------ undefined
    callback(users);
    }
  })
}

I'm also not sure how to work in the cookie data (to check for current user and grab their personal info). In our router file, we use:

router.get('/', function(req, res) {
  var currentUser = {};
  var theUser = {};
  if(req.cookies.current_user) {
    currentUser = JSON.parse(req.cookies.current_user);
    var query = { username: currentUser.username };
    User.findOne(query, function(error, user){
      theUser = user;
      res.render('index', { currentUser: theUser });
    });
    // res.render('index', { currentUser: theUser });
  } else {
    res.render('login');
  }
});

I realized I can't do req.cookies.current_user in the scripts file..... help!

**Comment by DZGoldman** [comment]
I can take a look - come on over
