### ISSUE TITLE
Help parsing tricky Google Maps object

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/Project_3#26]
I overrode the Google Maps InfoWindow prototype in order to affect the content of all the Points of Interest that come built in to a map (like the 23rd st subway station, the post office, restaurants in your zoom level, etc.). 

I was able to build in our "Save" button, but extracting the data for a POI is a lot trickier. For places that we add to the map when a user searches, we're able to get the unique place_id and store all of the unique info for that place, including name, latitude, longitude, etc.

The built-in POIs' data is much more obscured. I'm just looking for some ideas of how we might be able to handle this (if we can). Here's what I get when I console.log the infowindow content:

`
scripts.js:18 initializing
scripts.js:25 
ie {gm_accessors_: Object, map: qg, gm_bindings_: Object, j: Dd, H: Fd…}
scripts.js:78 
Object {}
scripts.js:79 
[prevObject: n.fn.init[1], context: document, selector: ".poi-info-window"]
scripts.js:97 
[div, context: div]
0
:
div
__jstcache
:
Array[0]
accessKey
:
""
align
:
""
attributes
:
NamedNodeMap
baseURI
:
"http://localhost:8080/"
childElementCount
:
3
childNodes
:
NodeList[3]
children
:
HTMLCollection[3]
classList
:
DOMTokenList[0]
className
:
""
clientHeight
:
98
clientLeft
:
0
clientTop
:
0
clientWidth
:
250
contentEditable
:
"inherit"
dataset
:
DOMStringMap
dir
:
"ltr"
draggable
:
false
firstChild
:
div.poi-info-window.gm-style
firstElementChild
:
div.poi-info-window.gm-style
hidden
:
false
id
:
""
innerHTML
:
"<div jstcache="33" class="poi-info-window gm-style"> <div jstcache="2" style="display:none"> <div jstcache="3" class="title full-width" jsan="7.title,7.full-width"></div> <div class="address"> <div jstcache="4" class="address-line full-width" style="display:none" jsan="7.address-line,7.full-width"></div> </div> </div> <div jstcache="5" class="transit-container"> <div jstcache="10" class="transit-title" style="display:none"> <span jstcache="11"></span> </div> <div jstcache="12" class="transit-title"> <span jstcache="13">23 Street</span> <div jstcache="14" class="transit-wheelchair-icon" style="display:none"></div> </div> <div jstcache="15" jsinstance="*0" class="transit-line-group" jsan="7.transit-line-group"> <div class="transit-line-group-vehicle-icons"> <img height="15" width="15" jstcache="16" src="https://maps.gstatic.com/mapfiles/transit/iw2/b/subway.png" jsinstance="*0"> </div> <div jstcache="17" class="transit-line-group-content"> <div jstcache="18" jsinstance="0" class="transit-div-line-name"> <div jstcache="24" class="long" jsan="7.long"> <span jstcache="25" role="listitem" jsinstance="*0"><img alt="4" height="15" width="15" jstcache="27" src="https://maps.gstatic.com/mapfiles/transit/iw2/b/us-ny-mta/4.png" class="renderable-component-icon"><span jstcache="28" style="display:none"><div jstcache="29" class="renderable-component-color-box" style="display:none"></div><span jstcache="30" class="renderable-component-text-box renderable-component-bold renderable-component-text-box-white" style="display:none" jsan="7.renderable-component-text-box,7.renderable-component-bold,7.renderable-component-text-box-white"><span jstcache="31" class="renderable-component-text-box-content" jsan="7.renderable-component-text-box-content"></span></span><span jstcache="32" class="renderable-component-text renderable-component-bold" style="display:none" jsan="7.renderable-component-text,7.renderable-component-bold"></span></span></span> </div> </div><div jstcache="18" jsinstance="1" class="transit-div-line-name"> <div jstcache="24" class="long" jsan="7.long"> <span jstcache="25" role="listitem" jsinstance="*0"><img alt="6" height="15" width="15" jstcache="27" src="https://maps.gstatic.com/mapfiles/transit/iw2/b/us-ny-mta/6.png" class="renderable-component-icon"><span jstcache="28" style="display:none"><div jstcache="29" class="renderable-component-color-box" style="display:none"></div><span jstcache="30" class="renderable-component-text-box renderable-component-bold renderable-component-text-box-white" style="display:none" jsan="7.renderable-component-text-box,7.renderable-component-bold,7.renderable-component-text-box-white"><span jstcache="31" class="renderable-component-text-box-content" jsan="7.renderable-component-text-box-content"></span></span><span jstcache="32" class="renderable-component-text renderable-component-bold" style="display:none" jsan="7.renderable-component-text,7.renderable-component-bold"></span></span></span> </div> </div><div jstcache="18" jsinstance="*2" class="transit-div-line-name"> <div jstcache="24" class="long" jsan="7.long"> <span jstcache="25" role="listitem" jsinstance="*0"><img alt="6X" height="15" width="15" jstcache="27" src="https://maps.gstatic.com/mapfiles/transit/iw2/b/us-ny-mta/6X.png" class="renderable-component-icon"><span jstcache="28" style="display:none"><div jstcache="29" class="renderable-component-color-box" style="display:none"></div><span jstcache="30" class="renderable-component-text-box renderable-component-bold renderable-component-text-box-white" style="display:none" jsan="7.renderable-component-text-box,7.renderable-component-bold,7.renderable-component-text-box-white"><span jstcache="31" class="renderable-component-text-box-content" jsan="7.renderable-component-text-box-content"></span></span><span jstcache="32" class="renderable-component-text renderable-component-bold" style="display:none" jsan="7.renderable-component-text,7.renderable-component-bold"></span></span></span> </div> </div> <div class="transit-clear-lines"></div> <div jstcache="19" class="transit-nlines-more-msg" style="display:none"> and <span jstcache="20"></span>&nbsp;more. </div> </div> </div> </div> <div class="view-link"> <a target="_blank" jstcache="6" href="https://maps.google.com/maps?ll=40.739703,-73.989576&amp;z=16&amp;t=m&amp;hl=en-US&amp;gl=US&amp;mapclient=apiv3&amp;cid=3430922904291280742"> <span> View on Google Maps </span> </a> </div> </div><button id="save-place">Add to favorites</button><div style="display:none;" class="infowindow-expanded"></div>"
innerText
:
"23 Street↵ ↵↵↵↵View on Google Maps↵Add to favorites"
isContentEditable
:
false
lang
:
""
lastChild
:
div.infowindow-expanded
lastElementChild
:
div.infowindow-expanded
localName
:
"div"
namespaceURI
:
"http://www.w3.org/1999/xhtml"
nextElementSibling
:
null
nextSibling
:
null
nodeName
:
"DIV"
nodeType
:
1
nodeValue
:
null
offsetHeight
:
98
offsetLeft
:
0
offsetParent
:
div.gm-style-iw
offsetTop
:
3
offsetWidth
:
250
onabort
:
null
onautocomplete
:
null
onautocompleteerror
:
null
onbeforecopy
:
null
onbeforecut
:
null
onbeforepaste
:
null
onblur
:
null
oncancel
:
null
oncanplay
:
null
oncanplaythrough
:
null
onchange
:
null
onclick
:
null
onclose
:
null
oncontextmenu
:
null
oncopy
:
null
oncuechange
:
null
oncut
:
null
ondblclick
:
null
ondrag
:
null
ondragend
:
null
ondragenter
:
null
ondragleave
:
null
ondragover
:
null
ondragstart
:
null
ondrop
:
null
ondurationchange
:
null
onemptied
:
null
onended
:
null
onerror
:
null
onfocus
:
null
oninput
:
null
oninvalid
:
null
onkeydown
:
null
onkeypress
:
null
onkeyup
:
null
onload
:
null
onloadeddata
:
null
onloadedmetadata
:
null
onloadstart
:
null
onmousedown
:
null
onmouseenter
:
null
onmouseleave
:
null
onmousemove
:
null
onmouseout
:
null
onmouseover
:
null
onmouseup
:
null
onmousewheel
:
null
onpaste
:
null
onpause
:
null
onplay
:
null
onplaying
:
null
onprogress
:
null
onratechange
:
null
onreset
:
null
onresize
:
null
onscroll
:
null
onsearch
:
null
onseeked
:
null
onseeking
:
null
onselect
:
null
onselectstart
:
null
onshow
:
null
onstalled
:
null
onsubmit
:
null
onsuspend
:
null
ontimeupdate
:
null
ontoggle
:
null
onvolumechange
:
null
onwaiting
:
null
onwebkitfullscreenchange
:
null
onwebkitfullscreenerror
:
null
onwheel
:
null
outerHTML
:
"<div dir="ltr" jstcache="0"><div jstcache="33" class="poi-info-window gm-style"> <div jstcache="2" style="display:none"> <div jstcache="3" class="title full-width" jsan="7.title,7.full-width"></div> <div class="address"> <div jstcache="4" class="address-line full-width" style="display:none" jsan="7.address-line,7.full-width"></div> </div> </div> <div jstcache="5" class="transit-container"> <div jstcache="10" class="transit-title" style="display:none"> <span jstcache="11"></span> </div> <div jstcache="12" class="transit-title"> <span jstcache="13">23 Street</span> <div jstcache="14" class="transit-wheelchair-icon" style="display:none"></div> </div> <div jstcache="15" jsinstance="*0" class="transit-line-group" jsan="7.transit-line-group"> <div class="transit-line-group-vehicle-icons"> <img height="15" width="15" jstcache="16" src="https://maps.gstatic.com/mapfiles/transit/iw2/b/subway.png" jsinstance="*0"> </div> <div jstcache="17" class="transit-line-group-content"> <div jstcache="18" jsinstance="0" class="transit-div-line-name"> <div jstcache="24" class="long" jsan="7.long"> <span jstcache="25" role="listitem" jsinstance="*0"><img alt="4" height="15" width="15" jstcache="27" src="https://maps.gstatic.com/mapfiles/transit/iw2/b/us-ny-mta/4.png" class="renderable-component-icon"><span jstcache="28" style="display:none"><div jstcache="29" class="renderable-component-color-box" style="display:none"></div><span jstcache="30" class="renderable-component-text-box renderable-component-bold renderable-component-text-box-white" style="display:none" jsan="7.renderable-component-text-box,7.renderable-component-bold,7.renderable-component-text-box-white"><span jstcache="31" class="renderable-component-text-box-content" jsan="7.renderable-component-text-box-content"></span></span><span jstcache="32" class="renderable-component-text renderable-component-bold" style="display:none" jsan="7.renderable-component-text,7.renderable-component-bold"></span></span></span> </div> </div><div jstcache="18" jsinstance="1" class="transit-div-line-name"> <div jstcache="24" class="long" jsan="7.long"> <span jstcache="25" role="listitem" jsinstance="*0"><img alt="6" height="15" width="15" jstcache="27" src="https://maps.gstatic.com/mapfiles/transit/iw2/b/us-ny-mta/6.png" class="renderable-component-icon"><span jstcache="28" style="display:none"><div jstcache="29" class="renderable-component-color-box" style="display:none"></div><span jstcache="30" class="renderable-component-text-box renderable-component-bold renderable-component-text-box-white" style="display:none" jsan="7.renderable-component-text-box,7.renderable-component-bold,7.renderable-component-text-box-white"><span jstcache="31" class="renderable-component-text-box-content" jsan="7.renderable-component-text-box-content"></span></span><span jstcache="32" class="renderable-component-text renderable-component-bold" style="display:none" jsan="7.renderable-component-text,7.renderable-component-bold"></span></span></span> </div> </div><div jstcache="18" jsinstance="*2" class="transit-div-line-name"> <div jstcache="24" class="long" jsan="7.long"> <span jstcache="25" role="listitem" jsinstance="*0"><img alt="6X" height="15" width="15" jstcache="27" src="https://maps.gstatic.com/mapfiles/transit/iw2/b/us-ny-mta/6X.png" class="renderable-component-icon"><span jstcache="28" style="display:none"><div jstcache="29" class="renderable-component-color-box" style="display:none"></div><span jstcache="30" class="renderable-component-text-box renderable-component-bold renderable-component-text-box-white" style="display:none" jsan="7.renderable-component-text-box,7.renderable-component-bold,7.renderable-component-text-box-white"><span jstcache="31" class="renderable-component-text-box-content" jsan="7.renderable-component-text-box-content"></span></span><span jstcache="32" class="renderable-component-text renderable-component-bold" style="display:none" jsan="7.renderable-component-text,7.renderable-component-bold"></span></span></span> </div> </div> <div class="transit-clear-lines"></div> <div jstcache="19" class="transit-nlines-more-msg" style="display:none"> and <span jstcache="20"></span>&nbsp;more. </div> </div> </div> </div> <div class="view-link"> <a target="_blank" jstcache="6" href="https://maps.google.com/maps?ll=40.739703,-73.989576&amp;z=16&amp;t=m&amp;hl=en-US&amp;gl=US&amp;mapclient=apiv3&amp;cid=3430922904291280742"> <span> View on Google Maps </span> </a> </div> </div><button id="save-place">Add to favorites</button><div style="display:none;" class="infowindow-expanded"></div></div>"
outerText
:
"23 Street↵ ↵↵↵↵View on Google Maps↵Add to favorites"
ownerDocument
:
document
parentElement
:
div
parentNode
:
div
prefix
:
null
previousElementSibling
:
null
previousSibling
:
null
scrollHeight
:
98
scrollLeft
:
0
scrollTop
:
0
scrollWidth
:
250
shadowRoot
:
null
spellcheck
:
true
style
:
CSSStyleDeclaration
tabIndex
:
-1
tagName
:
"DIV"
textContent
:
"            23 Street                       and  more.        View on Google Maps    Add to favorites"
title
:
""
translate
:
true
webkitdropzone
:
""
__proto__
:
HTMLDivElement
context
:
div
length
:
1
__proto__
:
Object[0]`

**Comment by CentroDL** [comment]
in your ajax, give the key $ value: 
 dataType: "json"

**Comment by CentroDL** [comment]
make a new request to maps with the latitude/longitude and save that
