### ISSUE TITLE
Deleting a favorite from user record

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/Project_3#28]
Trying to practice my server-side stuff by handling the route & AJAX call to remove a favorite from a user, but I'm not sure how to get the favorite by its ID from the front-end & pass it to the server.

First pass at the back-end code:

favoritesRouter.delete('/:place_id', function(req, res) {
  var cookiesUser = JSON.parse(req.cookies.current_user);
  var query = { username: cookiesUser.username };

  User.update(query, {$pull: {"favorites": _id}}, function(error,data){
    if(error){
      console.log(error);
    } else {
      res.json(data);
    }
  })
});

No current front-end code worth seeing -- just console logging to see what I have access to right now.

**Comment by CentroDL** [comment]
rubber duck debugged & done
